name: CI (generate, analyze, test)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI:
    env:
      FLUTTER_VERSION: "3.24.3"
    name: CI checks
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v3

      - name: Set Flutter cache variables
        shell: bash
        id: set_flutter_cache_vars
        run: |
          echo "cache_key=flutter-${{runner.os}}-stable-${{env.FLUTTER_VERSION}}-${{runner.arch}}" >> $GITHUB_OUTPUT
          cache_path="${{runner.tool_cache}}/flutter/stable-${{env.FLUTTER_VERSION}}-${{runner.arch}}"
          echo "cache_path=$(echo ${cache_path} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Cache Flutter
        uses: buildjet/cache@v3
        with:
          path: ${{steps.set_flutter_cache_vars.outputs.cache_path}}
          key: ${{steps.set_flutter_cache_vars.outputs.cache_key}}-${{hashFiles('**/pubspec.lock')}}
          restore-keys: |
            ${{steps.set_flutter_cache_vars.outputs.cache_key}}

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Generate required code
      - name: Generate required code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Check code formatting
      - name: Format Check
        run: flutter format --set-exit-if-changed .

      # Run static analysis (analyze)
      - name: Analyze code
        run: flutter analyze

      # Install lcov for test coverage analysis
      - name: Install lcov
        run: sudo apt-get install -y lcov

      # Run tests and generate coverage
      - name: Run all tests with coverage
        run: flutter test --coverage

      # Verify code coverage using codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info


name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}