name: CI and Build & Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # CI job
  CI:
    env:
      FLUTTER_VERSION: "3.24.3"
    name: CI checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Run flutter pub get to install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Generate required code
      - name: Generate required code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Check code formatting
      - name: Format Check
        run: dart format --set-exit-if-changed .

      # Run static analysis (analyze)
      - name: Analyze code
        run: flutter analyze

      # Install lcov for test coverage analysis
      - name: Install lcov
        run: sudo apt-get install -y lcov

      # Run tests and generate coverage
      - name: Run all tests with coverage
        run: flutter test --coverage

      # Verify code coverage using codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info


  # Build & Release job
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
          
      - name: Push to Releases
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
